pub const SELECTION_MAX: usize = 3;
pub const MAX_TILES: usize = 14;
pub const TILE_SIZE: u16 = 50;
pub const TILE_HALF_SIZE: f64 = (TILE_SIZE / 2) as f64;
pub const TILE_GAP: u16 = 4;
pub const TILE_SELECTION_BORDER: f64 = 3.0;
pub const TILE_SIZE_N_GAP: u16 = TILE_SIZE + TILE_GAP;
pub const MOVE_SIZE: f64 = 0.5;
pub const TILE_PULL_SPEED: f64 = 8.0;
pub const TILE_SIZE_IN_MOVES: u16 = (TILE_SIZE_N_GAP as f64 / MOVE_SIZE) as u16 - 2; // I genuinely have no idea why but this it works much smoother
pub const FONT: &str = "28px serif";
